---

- name: Put in place the Shibboleth Yum Repository
  get_url:
    url: "{{ shibboleth_yumrepo_url }}"
    dest: "/etc/yum.repos.d/security_shibboleth.repo"
    mode: 0644

- name: Install Shibboleth SP
  yum: name=shibboleth state=installed
  register: shib_install

- name: Ensure Shibboleth Starts on Boot
  service: name=shibd enabled=yes

- name: Put in place UCLA-specific IAM shibboleth2.xml file
  template:
    src: "shibboleth2_xml.j2"
    dest: "/etc/shibboleth/shibboleth2.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: "yes"
  when: shib_install.changed
  notify:
    - restart shibd
    - restart httpd

- name: Put in place the UCLA-default IAM attribute-map.xml file
  copy:
    src: "attribute-map.xml"
    dest: "/etc/shibboleth/attribute-map.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: "yes"
  when: shib_install.changed
  notify:
    - restart shibd
    - restart httpd

- name: Put in place the UCLA-default IAM attribute-policy.xml file
  copy:
    src: "attribute-policy.xml"
    dest: "/etc/shibboleth/attribute-policy.xml"
    owner: "root"
    group: "root"
    mode: 0644
    backup: "yes"
  when: shib_install.changed
  notify:
    - restart shibd
    - restart httpd
